[package]
name = "mushrust"
version = "0.1.0"
authors = ["erdeszt <erdeszt@gmail.com>"]
edition = "2018"

[dependencies]
gpio-cdev = "0.4.0"
sqlx = { version = "0.4.0-beta.1", default-features = false, features = ["sqlite", "runtime-async-std", "macros"] }
async-std = { version = "1.5.0", features = ["attributes"] }

[dependencies.openssl]
version = "0.10.29"
features = ["vendored"]
